export const ROUTES = {
  root: '/',
  home: '/post',
  login: '/login',
  report: '/post/register',
  review: '/review',
  reviewDetail: (reviewId: string) => `/review/${reviewId}`,
  reviewWrite: '/review/register',
  postDetail: (postId: string) => `/post/${postId}`,
  relatedReports: (productId: string) => `/product/${productId}/related`,
  mypage: '/mypage',
  mypageMyReports: '/mypage/my-reports',
  mypageMyReceiptReviews: '/mypage/my-receipt-reviews',
  mypageWishlist: '/mypage/wishlist',
  mypageProfileEdit: '/mypage/profile-edit',
} as const;
